// Amplify configuration — generated by `amplify pull` or manually maintained.
// Replace placeholder values with your real AppSync and Cognito endpoints.
// DO NOT commit real secrets. Use environment-specific amplifyconfiguration.dart
// generated via CI or loaded from secure storage at startup.

const amplifyconfig = '''
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "us-east-1:bfdbbcea-5752-4b18-8630-7dfde76fabd0",
              "Region": "us-east-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "us-east-1_ZPcUgc5xx",
            "AppClientId": "1j912dhe00l6giu3q2on5np14",
            "Region": "us-east-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "socialProviders": [],
            "usernameAttributes": ["EMAIL"],
            "signupAttributes": ["EMAIL", "NAME"],
            "passwordProtectionSettings": {
              "passwordPolicyMinLength": 8,
              "passwordPolicyCharacters": [
                "REQUIRES_LOWERCASE",
                "REQUIRES_UPPERCASE",
                "REQUIRES_NUMBERS"
              ]
            },
            "mfaConfiguration": "OFF",
            "verificationMechanisms": ["EMAIL"]
          }
        }
      }
    }
  },
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "blwrecipesapi": {
          "endpointType": "GraphQL",
          "endpoint": "https://erlv45lv3feihjdtpi5v56aoce.appsync-api.us-east-1.amazonaws.com/graphql",
          "region": "us-east-1",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        }
      }
    }
  },
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "blw-recipes-media-324062893587-us-east-1",
        "region": "us-east-1",
        "defaultAccessLevel": "guest"
      }
    }
  }
}
''';
